import type {
  ColorLayer,
  Contour,
  Point,
  Segment,
  StrokePath,
  SvgEmitOptions,
  VectorizeResult,
} from '../types.js';

/**
 * SVG serialization.
 *
 * Two things matter here beyond producing valid markup:
 *
 *  - **Layer structure.** Every color becomes one `<g>` carrying `fill`, an id and
 *    a `data-color`. That is what lets a designer recolour in place, a cutting
 *    machine assign a mat per color, and a print shop separate plates, without
 *    anyone having to select shapes by eye.
 *
 *  - **Hole handling.** Outer contours and holes are wound in opposite
 *    directions, so `fill-rule: nonzero` (the SVG default) resolves them with no
 *    extra attributes and no guessing about containment.
 */

export interface ResolvedEmitOptions extends Required<Omit<SvgEmitOptions, 'backgroundColor'>> {
  backgroundColor: string | null;
  pathPerShape: boolean;
}

/** Where the closing `Z` belongs, and where it must not appear. */
export type PathClosing = 'closed' | 'open';

const DEFAULTS: ResolvedEmitOptions = {
  precision: 2,
  relative: true,
  metadata: true,
  groupByColor: true,
  pretty: false,
  dimensions: true,
  backgroundColor: null,
  scale: 1,
  pathPerShape: false,
  roundStrokes: true,
};

export function emitSvg(
  result: VectorizeResult,
  options: SvgEmitOptions & { pathPerShape?: boolean } = {}
): string {
  const config: ResolvedEmitOptions = {
    ...DEFAULTS,
    precision: options.precision ?? result.resolvedOptions.precision ?? DEFAULTS.precision,
    relative: options.relative ?? DEFAULTS.relative,
    metadata: options.metadata ?? DEFAULTS.metadata,
    groupByColor: options.groupByColor ?? DEFAULTS.groupByColor,
    pretty: options.pretty ?? DEFAULTS.pretty,
    dimensions: options.dimensions ?? DEFAULTS.dimensions,
    backgroundColor: options.backgroundColor ?? DEFAULTS.backgroundColor,
    scale: options.scale ?? DEFAULTS.scale,
    pathPerShape: options.pathPerShape ?? DEFAULTS.pathPerShape,
    roundStrokes: options.roundStrokes ?? DEFAULTS.roundStrokes,
  };

  const newline = config.pretty ? '\n' : '';
  const indent = config.pretty ? '  ' : '';

  const width = result.width * config.scale;
  const height = result.height * config.scale;

  const parts: string[] = [];

  const dimensionAttributes = config.dimensions
    ? ` width="${trimNumber(width, 3)}" height="${trimNumber(height, 3)}"`
    : '';

  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg"${dimensionAttributes} ` +
      `viewBox="0 0 ${trimNumber(result.width, 3)} ${trimNumber(result.height, 3)}">`
  );

  if (config.metadata) {
    const { colors, pieces, strokes, nodes } = result.stats;
    const strokeNote = strokes > 0 ? `, ${strokes} centreline${strokes === 1 ? '' : 's'}` : '';
    parts.push(
      `${indent}<title>Vectorized artwork</title>`,
      `${indent}<desc>${colors} color layer${colors === 1 ? '' : 's'}, ` +
        `${pieces} piece${pieces === 1 ? '' : 's'}${strokeNote}, ${nodes} nodes. ` +
        `Generated by PerfectVector.</desc>`
    );
  }

  if (config.backgroundColor) {
    parts.push(
      `${indent}<rect width="${trimNumber(result.width, 3)}" ` +
        `height="${trimNumber(result.height, 3)}" fill="${escapeAttribute(config.backgroundColor)}"/>`
    );
  }

  for (const layer of result.layers) {
    // A layer recovered entirely as centrelines has no shapes at all, so the guard
    // has to consider both.
    if (layer.shapes.length === 0 && layer.strokes.length === 0) continue;
    parts.push(...emitLayer(layer, config, indent));
  }

  parts.push('</svg>');

  return parts.join(newline) + (config.pretty ? '\n' : '');
}

function emitLayer(layer: ColorLayer, config: ResolvedEmitOptions, indent: string): string[] {
  const lines: string[] = [];
  const pieces = layer.shapes.length;

  // Centrelines are grouped separately by width. Stroke weight is a presentation
  // attribute, so paths that share one can share a parent and state it once, and a
  // designer restyling the artwork has a single place to change it.
  const strokeGroups = new Map<number, StrokePath[]>();
  for (const stroke of layer.strokes) {
    const rounded = Math.round(stroke.width * 100) / 100;
    const bucket = strokeGroups.get(rounded);
    if (bucket) bucket.push(stroke);
    else strokeGroups.set(rounded, [stroke]);
  }

  const paths: string[] = [];
  if (config.pathPerShape) {
    for (const shape of layer.shapes) {
      const d = shape.contours.map((c) => contourToPathData(c, config)).join('');
      if (d) paths.push(d);
    }
  } else {
    // One path per color. Because same-color regions never overlap, merging them
    // into a single subpath list is lossless and measurably smaller than one
    // element per region.
    const d = layer.shapes
      .flatMap((shape) => shape.contours)
      .map((c) => contourToPathData(c, config))
      .join('');
    if (d) paths.push(d);
  }

  if (paths.length === 0 && strokeGroups.size === 0) return lines;

  if (!config.groupByColor) {
    for (const d of paths) {
      lines.push(`${indent}<path fill="${layer.hex}" d="${d}"/>`);
    }
    for (const [width, strokes] of strokeGroups) {
      for (const stroke of strokes) {
        lines.push(
          `${indent}<path fill="none" stroke="${layer.hex}" ` +
            `stroke-width="${formatNumber(width * config.scale, config.precision)}"` +
            `${strokeStyleAttributes(config)} d="${strokePathData(stroke, config)}"/>`
        );
      }
    }
    return lines;
  }

  const groupId = `layer-${layer.index + 1}`;
  const strokeCount = layer.strokes.length;
  lines.push(
    `${indent}<g id="${groupId}" data-color="${layer.hex}" ` +
      `data-name="${escapeAttribute(layer.name)}" data-pieces="${pieces}"` +
      `${strokeCount > 0 ? ` data-strokes="${strokeCount}"` : ''} fill="${layer.hex}">`
  );

  const inner = config.pretty ? indent + indent : '';
  for (const d of paths) {
    lines.push(`${inner}<path d="${d}"/>`);
  }

  for (const [width, strokes] of strokeGroups) {
    // `fill="none"` is required: the parent group sets a fill, and a stroked
    // centreline that inherited it would paint a filled blob under the line.
    lines.push(
      `${inner}<g fill="none" stroke="${layer.hex}" ` +
        `stroke-width="${formatNumber(width * config.scale, config.precision)}"` +
        `${strokeStyleAttributes(config)}>`
    );
    const deeper = config.pretty ? inner + indent : '';
    for (const stroke of strokes) {
      lines.push(`${deeper}<path d="${strokePathData(stroke, config)}"/>`);
    }
    lines.push(`${inner}</g>`);
  }

  lines.push(`${indent}</g>`);

  return lines;
}

/**
 * Round caps and joins by default. A drawn stroke almost always had them, and butt
 * caps leave visible notches where centrelines meet at a junction, because each
 * path stops exactly at the shared point instead of covering the corner.
 */
function strokeStyleAttributes(config: ResolvedEmitOptions): string {
  return config.roundStrokes ? ' stroke-linecap="round" stroke-linejoin="round"' : '';
}

/** Path data for a centreline. Open paths are not closed with `Z`. */
export function strokePathData(stroke: StrokePath, config: ResolvedEmitOptions): string {
  return contourToPathData(
    {
      start: stroke.start,
      segments: stroke.segments,
      signedArea: 0,
      isHole: false,
    },
    config,
    stroke.closed
  );
}

/**
 * Serialize one closed contour.
 *
 * Relative commands are the default because path data is dominated by small
 * deltas between neighbouring points, and relative coordinates need far fewer
 * digits than absolute ones on a large canvas.
 */
export function contourToPathData(
  contour: Contour,
  config: ResolvedEmitOptions,
  close = true
): string {
  const { precision, relative, scale } = config;
  const tokens: string[] = [];

  const scaled = (p: Point): Point => ({ x: p.x * scale, y: p.y * scale });

  const start = scaled(contour.start);
  tokens.push('M', formatNumber(start.x, precision), formatNumber(start.y, precision));

  let cursor = roundPoint(start, precision);
  let lastCommand = '';

  for (const segment of contour.segments) {
    if (segment.kind === 'line') {
      const to = roundPoint(scaled(segment.to), precision);
      if (to.x === cursor.x && to.y === cursor.y) continue;

      if (relative) {
        const dx = to.x - cursor.x;
        const dy = to.y - cursor.y;
        // Axis-aligned runs are extremely common in traced art; h/v halve their cost.
        if (dy === 0) {
          pushCommand(tokens, 'h', lastCommand, [formatNumber(dx, precision)]);
          lastCommand = 'h';
        } else if (dx === 0) {
          pushCommand(tokens, 'v', lastCommand, [formatNumber(dy, precision)]);
          lastCommand = 'v';
        } else {
          pushCommand(tokens, 'l', lastCommand, [
            formatNumber(dx, precision),
            formatNumber(dy, precision),
          ]);
          lastCommand = 'l';
        }
      } else {
        pushCommand(tokens, 'L', lastCommand, [
          formatNumber(to.x, precision),
          formatNumber(to.y, precision),
        ]);
        lastCommand = 'L';
      }
      cursor = to;
      continue;
    }

    const c1 = roundPoint(scaled(segment.c1), precision);
    const c2 = roundPoint(scaled(segment.c2), precision);
    const to = roundPoint(scaled(segment.to), precision);

    if (relative) {
      pushCommand(tokens, 'c', lastCommand, [
        formatNumber(c1.x - cursor.x, precision),
        formatNumber(c1.y - cursor.y, precision),
        formatNumber(c2.x - cursor.x, precision),
        formatNumber(c2.y - cursor.y, precision),
        formatNumber(to.x - cursor.x, precision),
        formatNumber(to.y - cursor.y, precision),
      ]);
      lastCommand = 'c';
    } else {
      pushCommand(tokens, 'C', lastCommand, [
        formatNumber(c1.x, precision),
        formatNumber(c1.y, precision),
        formatNumber(c2.x, precision),
        formatNumber(c2.y, precision),
        formatNumber(to.x, precision),
        formatNumber(to.y, precision),
      ]);
      lastCommand = 'C';
    }
    cursor = to;
  }

  // Filled contours always close. An open centreline must not, or it grows a
  // straight segment back to its start.
  if (close) tokens.push('Z');
  return joinTokens(tokens);
}

/**
 * Omit the command letter when it repeats, which the SVG path grammar allows.
 * Long runs of `c` or `l` are the norm in traced output, so this is a real saving.
 */
function pushCommand(
  tokens: string[],
  command: string,
  lastCommand: string,
  args: string[]
): void {
  if (command !== lastCommand) tokens.push(command);
  tokens.push(...args);
}

/**
 * Join tokens with the minimum legal whitespace. A leading minus sign is itself a
 * valid separator, so no space is needed before a negative number.
 */
function joinTokens(tokens: string[]): string {
  let out = '';
  for (const token of tokens) {
    if (out.length === 0) {
      out = token;
      continue;
    }
    const previous = out.charCodeAt(out.length - 1);
    const isPreviousLetter =
      (previous >= 65 && previous <= 90) || (previous >= 97 && previous <= 122);
    if (token.startsWith('-') || isPreviousLetter) {
      out += token;
    } else {
      out += ' ' + token;
    }
  }
  return out;
}

function roundPoint(p: Point, precision: number): Point {
  const factor = Math.pow(10, precision);
  return { x: Math.round(p.x * factor) / factor, y: Math.round(p.y * factor) / factor };
}

/** Shortest legal representation: trailing zeros and a leading zero both dropped. */
export function formatNumber(value: number, precision: number): string {
  if (!Number.isFinite(value)) return '0';
  let s = value.toFixed(precision);
  if (s.indexOf('.') !== -1) {
    s = s.replace(/0+$/, '').replace(/\.$/, '');
  }
  if (s === '-0' || s === '') s = '0';
  s = s.replace(/^(-?)0\./, '$1.');
  return s;
}

function trimNumber(value: number, precision: number): string {
  return formatNumber(value, precision);
}

function escapeAttribute(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Count anchor points across a segment list, matching the reported node metric. */
export function countNodes(segments: Segment[]): number {
  return segments.length;
}
